app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    // Registration and Login Route.
    Route::auth();

    // Verify the user
    Route::get('fregister/confirm/{token}', ['as' => 'verify', 'uses' => 'Frontend\VerifyUserController@verify']);
    Route::get('confirm', ['as' => 'confirm', 'uses' => 'Frontend\VerifyUserController@confirm']);
    Route::get('confirm/success', ['as' => 'confirm.success', 'uses' => 'Frontend\VerifyUserController@confirmed_success']);

    // AdminController Routes
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::get('view', ['as' => 'dashboard', 'uses' => 'Admin\AdminController@index']);

    // AdminUserController Routes
        Route::get('users', ['as' => 'users.all', 'uses' => 'Admin\AdminUserController@getUsers']);
        Route::post('user/delete/{id}', ['as' => 'user.destroy', 'uses' => 'Admin\AdminUserController@destroy']);

    // AdminDayController Routes
        Route::get('days/show', ['as' => 'days', 'uses' => 'Admin\AdminDayController@index']);
        Route::get('day/create', ['as' => 'day.create', 'uses' => 'Admin\AdminDayController@create']);
        Route::post('days/store', ['as' => 'days.store', 'uses' => 'Admin\AdminDayController@store']);
        Route::get('days/edit/{id}', ['as' => 'days.edit', 'uses' => 'Admin\AdminDayController@edit']);
        Route::post('days/update/{id}', ['as' => 'days.update', 'uses' => 'Admin\AdminDayController@update']);
        Route::post('days/destroy/{id}', ['as' => 'days.destroy', 'uses' => 'Admin\AdminDayController@destroy']);

    // AdminScheduleController Routes
        Route::get('schedule/{slug}', ['as' => 'schedule', 'uses' => 'Admin\AdminScheduleController@index']);

    // AdminPdfController Routes
        Route::get('pdf', ['as' => 'pdf', 'uses' => 'Admin\AdminPdfController@index']);
        Route::post('pdf/store', ['as' => 'pdf.store', 'uses' => 'Admin\AdminPdfController@store']);
        Route::post('pdf/destroy/{id}', ['as' => 'pdf.destroy', 'uses' => 'Admin\AdminPdfController@destroy']);

    // AdminPlenaryPanelController Routes
        Route::get('plenary/edit/{id}', ['as' => 'plenary.edit', 'uses' => 'Admin\AdminPlenaryPanelController@edit']);
        Route::post('plenary/store/{slug}', ['as' => 'plenary.store', 'uses' => 'Admin\AdminPlenaryPanelController@store']);
        Route::patch('plenary/update/{id}', ['as' => 'plenary.update', 'uses' => 'Admin\AdminPlenaryPanelController@update']);
        Route::post('plenary/destroy/{id}', ['as' => 'plenary.destroy', 'uses' => 'Admin\AdminPlenaryPanelController@destroy']);

    // AdminStreamController Routes
        Route::post('stream.create', ['as' => 'stream.create', 'uses' => 'Admin\AdminStreamController@store']);
        Route::post('stream.destroy/{id}', ['as' => 'stream.destroy', 'uses' => 'Admin\AdminStreamController@destroy']);

    // AdminStreamPanelController Routes
        Route::post('streamPanel.create', ['as' => 'streamPanel.create', 'uses' => 'Admin\AdminStreamPanelController@store']);
        Route::get('streamPanel/edit/{id}', ['as' => 'streamPanel.edit', 'uses' => 'Admin\AdminStreamPanelController@edit']);
        Route::patch('streamPanel/update/{id}', ['as' => 'streamPanel.update', 'uses' => 'Admin\AdminStreamPanelController@update']);
        Route::post('streamPanel/destroy/{id}', ['as' => 'streamPanel.destroy', 'uses' => 'Admin\AdminStreamPanelController@destroy']);

    // AdminSpeakerController Routes
        Route::group(['prefix' => 'speakers', 'as' => 'speakers.'], function(){
            Route::get('/show', ['as' => 'index', 'uses' => 'Admin\AdminSpeakerController@index']);
            Route::get('/create', ['as' => 'create', 'uses' => 'Admin\AdminSpeakerController@create']);
            Route::post('/store', ['as' => 'store', 'uses' => 'Admin\AdminSpeakerController@store']);
            Route::post('/delete', ['as' => 'destroy', 'uses' => 'Admin\AdminSpeakerController@destroy']);
            Route::get('/edit/{username}', ['as' => 'edit', 'uses' => 'Admin\AdminSpeakerController@edit']);
            Route::post('/edit/{username}', ['as' => 'update', 'uses' => 'Admin\AdminSpeakerController@update']);
            Route::post('rating/store/{id}', ['as' => 'rating', 'uses' => 'Frontend\RatingController@store']);
        });

    // AdminSponsorController Routes
        Route::get('sponsors/view', ['as' => 'sponsors.view', 'uses' => 'Admin\AdminSponsorController@index']);
        Route::get('sponsors/create', ['as' => 'sponsors.create', 'uses' => 'Admin\AdminSponsorController@create']);
        Route::post('sponsors/store', ['as' => 'sponsors.store', 'uses' => 'Admin\AdminSponsorController@store']);
        Route::get('sponsors/edit/{id}', ['as' => 'sponsors.edit', 'uses' => 'Admin\AdminSponsorController@edit']);
        Route::post('sponsors/update/{id}', ['as' => 'sponsors.update', 'uses' => 'Admin\AdminSponsorController@update']);
        Route::post('sponsors/delete/{id}', ['as' => 'sponsors.destroy', 'uses' => 'Admin\AdminSponsorController@destroy']);
        Route::get('sponsor/page_content', ['as' => 'sponsors.get_page_content', 'uses' => 'Admin\AdminSponsorController@get_page_content']);
        Route::post('sponsor/page_content', ['as' => 'sponsors.store_page_content', 'uses' => 'Admin\AdminSponsorController@store_page_content']);
        Route::get('sponsor/page_content/edit', ['as' => 'sponsors.edit_page_content', 'uses' => 'Admin\AdminSponsorController@edit_page_content']);
        Route::post('sponsor/page_content/{id}', ['as' => 'sponsors.update_page_content', 'uses' => 'Admin\AdminSponsorController@update_page_content']);

    // AdminPartnerController Routes
        Route::get('partners/show', ['as' => 'partners.show', 'uses' => "Admin\AdminPartnerController@index"]);
        Route::post('partners/store', ['as' => 'partners.store', 'uses' => "Admin\AdminPartnerController@store"]);
        Route::get('partners/create', ['as' => 'partners.create', 'uses' => "Admin\AdminPartnerController@create"]);
        Route::get('partners/edit/{slug}', ['as' => 'partners.edit', 'uses' => "Admin\AdminPartnerController@edit"]);
        Route::post('partners/update/{slug}', ['as' => 'partners.update', 'uses' => "Admin\AdminPartnerController@update"]);
        Route::post('partners/destroy/{slug}', ['as' => 'partners.destroy', 'uses' => "Admin\AdminPartnerController@destroy"]);

    // AdminCategoryController Routes
        Route::get('categories/view', ['as' => 'categories.view', 'uses' => 'Admin\AdminCategoryController@index']);
        Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\AdminCategoryController@store']);
        Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'Admin\AdminCategoryController@create']);
        Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\AdminCategoryController@edit']);
        Route::post('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\AdminCategoryController@update']);
        Route::post('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\AdminCategoryController@destroy']);

    // NewsletterController Routes
        Route::get('newsletter/subscribers', ['as' => 'newsletter.subscribers', 'uses' => 'Admin\AdminNewsletterController@index']);
        Route::post('newsletter/store', ['as' => 'newsletter.store', 'uses' => 'Admin\AdminNewsletterController@store']);
        Route::post('newsletter/delete/{id}', ['as' => 'newsletter.delete', 'uses' => 'Admin\AdminNewsletterController@destroy']);

    // PricePlanController Routes
        Route::get('plans/view', ['as' => 'plans.view', 'uses' => 'Admin\AdminPricePlanController@index']);
        Route::post('plans/store', ['as' => 'plan.store', 'uses' => 'Admin\AdminPricePlanController@store']);
        Route::get('plans/create', ['as' => 'plan.create', 'uses' => 'Admin\AdminPricePlanController@create']);
        Route::get('plans/edit/{id}', ['as' => 'plan.edit', 'uses' => 'Admin\AdminPricePlanController@edit']);
        Route::post('plans/update/{id}', ['as' => 'plan.update', 'uses' => 'Admin\AdminPricePlanController@update']);
        Route::post('plans/destroy/{id}', ['as' => 'plan.destroy', 'uses' => 'Admin\AdminPricePlanController@destroy']);

    // PricePlanOptionController Routes
        Route::get('PlanOption/create', ['as' => 'PlanOption.create', 'uses' => 'Admin\AdminPricePlanOptionController@create']);
        Route::post('PlanOption/store', ['as' => 'PlanOption.store', 'uses' => 'Admin\AdminPricePlanOptionController@store']);
        Route::get('PlanOption/edit/{id}', ['as' => 'PlanOption.edit', 'uses' => 'Admin\AdminPricePlanOptionController@edit']);
        Route::post('PlanOption/update/{id}', ['as' => 'PlanOption.update', 'uses' => 'Admin\AdminPricePlanOptionController@update']);
        Route::post('PlanOption/destroy/{id}', ['as' => 'PlanOption.destroy', 'uses' => 'Admin\AdminPricePlanOptionController@destroy']);

    // SettingsController Routes
        Route::get('settings', ['as' => 'settings', 'uses' => 'Admin\AdminSettingsController@index']);

    // AdminSliderController Routes
        Route::get('sliders', ['as' => 'sliders.show', 'uses' => 'Admin\AdminSliderController@index']);
        Route::post('slider/store', ['as' => 'sliders.store', 'uses' => 'Admin\AdminSliderController@store']);
        Route::get('slider/edit/{id}', ['as' => 'slider.edit', 'uses' => 'Admin\AdminSliderController@edit']);
        Route::get('slider/create', ['as' => 'sliders.create', 'uses' => 'Admin\AdminSliderController@create']);
        Route::post('slider/update/{id}', ['as' => 'sliders.update', 'uses' => 'Admin\AdminSliderController@update']);
        Route::post('slider/destroy/{id}', ['as' => 'sliders.destroy', 'uses' => 'Admin\AdminSliderController@destroy']);

    // AdminHomePageContentController Routes

resources/views/admin/partials/footer.blade.php
</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="/assets/admin/bower_components/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/assets/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/assets/admin/bower_components/metisMenu/dist/metisMenu.min.js"></script>


@if(Request::is('admin'))
{{--<!-- Morris Charts JavaScript -->--}}
<script src="/assets/admin/bower_components/raphael/raphael-min.js"></script>
<script src="/assets/admin/bower_components/morrisjs/morris.min.js"></script>
<script src="/assets/admin/js/morris-data.js"></script>

@else
<script src="/assets/admin/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="/assets/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
@endif

<!-- include summernote css/js-->
<link rel="stylesheet" href="/assets/admin/dist/css/summernote.css">
<script src="/assets/admin/dist/js/summernote.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/assets/admin/dist/js/sb-admin-2.js"></script>
<!-- Bootstrap Datepicker -->
<script type="text/javascript" src="/assets/admin/dist/js/bootstrap-datepicker.js"></script>
<!-- Confirm Delete -->
<script src="/assets/admin/dist/js/bootstrap-confirm-delete.js"></script>
<!-- Select 2-->
<script src="/assets/admin/dist/js/select2.min.js"></script>
<!-- Bootstrap TimePciker -->
<script src="/assets/admin/dist/js/bootstrap-timepicker.min.js"></script>
<!-- File Upload Bootsnip -->
<script src="/assets/admin/dist/js/custom.js"></script>
<!-- Bootstrap Form Helpers -->
<script src="/assets/admin/dist/js/bootstrap-formhelpers.js"></script>
<!-- Toaster -->
<script src="/assets/admin/dist/js/toastr.min.js"></script>
<script>
    toastr.options = {
        "closeButton": true,
        "closeButton": true,
        "positionClass": "toast-bottom-right",
        "progressBar": true,
        "preventDuplicates": true,
    };
</script>
{!! Toastr::render() !!}


<!-- Bootstrap-Iconpicker Iconset for Glyphicon -->
<script type="text/javascript" src="/assets/admin/dist/js/iconset/iconset-all.min.js"></script>

<!-- Bootstrap-Iconpicker -->
<script type="text/javascript" src="/assets/admin/dist/js/bootstrap-iconpicker.min.js"></script>
<script src="https://js.pusher.com/3.0/pusher.min.js"></script>
@include('layouts.confirm_deletion')
@yield('scripts')
</body>

</html>

resources/views/admin/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Event System">
    <meta name="author" content="Tiaan Theunissen">
    <title>Event Administrator</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/admin/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/assets/admin/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <!-- Timeline CSS -->
    <link href="/assets/admin/dist/css/timeline.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/assets/admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="/assets/admin/bower_components/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/assets/admin/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="/assets/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
    <!-- Boostrap Datepicker -->
    <link rel="stylesheet" href="/assets/admin/dist/css/datepicker.css">
    <!-- Confirm Delete -->
    <script src="/assets/admin/dist/css/bootstrap-confirm-delete.css"></script>
    <!-- Select 2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/css/select2.min.css" rel="stylesheet" />
    <!-- Toaster -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <!-- Custom Admin Style Sheet -->
    <link rel="stylesheet" href="/css/admin.css">
    <!-- BootStrap TimePicker -->
    <link type="text/css" href="/assets/admin/dist/css/bootstrap-timepicker.min.css" />
    <!-- Bootstrap Form Helpers -->
    <link type="text/css" href="/assets/admin/dist/css/bootstrap-formhelpers.css" />
    <link type="text/css" href="/assets/admin/dist/css/bootstrap-formhelpers.min.css" />
    <!--  simple-line Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.2.3/css/simple-line-icons.css">
    <!-- Bootstrap-Iconpicker -->
    <link rel="stylesheet" href="/assets/admin/dist/css/bootstrap-iconpicker.min.css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div id="wrapper">

resources/views/admin/partials/page-header.blade.php
<div class="row">
    <div class="col-md-10 col-xs-10 col-lg-10 col-sm-10">
        <h1 class="page-header">
            {{ $PageHeader }}
        </h1>
    </div>
</div>

resources/views/admin/partials/sidebar.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation"
     style="margin-bottom: 0;margin: 0px;margin-bottom: 0px;padding-bottom: 0px;">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{route('home')}}">Copyright &copy; 2016 Eventsys.co.za</a>
    </div>

    <ul class="nav navbar-top-links navbar-right">
        <li style="background-color: #FF9900;"><a class="no-hover" style=" color: white!important;" href="#">{{auth()->user()->name}}</a></li>
        <li style="background-color: #6F6F6F;"><a class="no-hover" style="color: white" href="{{route('home')}}">Visit Frontend</a></li>
        <li style="background-color: #FF9900;"><a class="no-hover" style=" color: white!important;" href="/logout">Sign out</a></li>
    </ul>

    <div class="navbar-default sidebar" role="navigation" style="background-color: #f8f8f8; text-transform: capitalize" >
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a class="no-hover" href="{{route('admin.dashboard')}}">
                        <img src="/assets/frontend/img/npo.png" width="100%" alt="Logo">
                    </a>
                </li>
                <li>
                    <a href="{{route('admin.dashboard')}}"> Administrator  Overview</a>
                </li>

                <li>
                    <a href="#"> Event Information<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse" aria-expanded="true">
                        @if(count($information) >= 1)
                            <li><a href="{{route('admin.event.edit')}}">Update existing content</a></li>
                        @else
                            <li><a href="{{ route('admin.event.info') }}">Add Event Information</a></li>
                        @endif
                    </ul>
                </li>

                <li>
                    <a href="#"> Members<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse" aria-expanded="true">
                        <li> <a href="{{ route('admin.users.all') }}">View all members </a></li>
                    </ul>
                </li>

                <li>
                    <a href="/admin/pages/"> Site Pages<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse" aria-expanded="true">
                        <li>
                        <a href="#">Home Page <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{{route('admin.pages.home.show')}}">Existing callout Blocks</a></li>
                                <li><a href="{{route('admin.pages.home.create')}}">Add New callout block</a></li>
                                <li><a class="disabled" href="{{ '/admin/pages/home/edit/' }}">Edit Content</a></li>
                            </ul>
                        </li>
                        <li>
                        <a href="#">About Us Page <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                @if(count($about) >= 1)
                                <li><a href="{{route('admin.pages.about.edit')}}">Update existing content</a></li>
                                @else
                                <li><a href="{{route('admin.pages.about.create')}}">Add new content</a></li>
                                @endif
                            </ul>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#">manage days<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.days')}}">Existing days</a></li>
                        <li><a href="{{route('admin.day.create')}}">Add a new day to the event</a></li>
                        <li><a class="disabled" href="{{ '/admin/days/edit/' }}">Edit Day</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#">manage speakers <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.speakers.index')}}">Existing speakers</a></li>
                        <li><a href="{{route('admin.speakers.create')}}">New speaker</a></li>
                        <li><a class="disabled" href="{{ '/admin/speakers/edit/' }}">Edit Speaker</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage schedule <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        @foreach($days as $day)
                            <li><a href="{{route('admin.schedule', $day->slug)}}">{{date_format(\Carbon\Carbon::parse($day->date), 'd F')}}</a></li>
                        @endforeach
                            <li><a href="{{route('admin.pdf')}}">Upload PDF</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage Sponsor Categories <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.categories.view')}}">Existing Categories</a></li>
                        <li><a href="{{route('admin.categories.create')}}">New Category</a></li>
                        <li><a class="disabled" href="{{ '/admin/categories/edit/' }}">Edit category</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage Sponsors <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        @if(count($sponsorPage) >= 1)
                            <li><a href="{{ route('admin.sponsors.edit_page_content') }}">sponsor page Edit</a></li>
                        @else
                            <li><a href="{{ route('admin.sponsors.get_page_content') }}">sponsor page content</a></li>
                        @endif
                        <li><a href="{{route('admin.sponsors.view')}}">Existing Sponsors</a></li>
                        <li><a href="{{route('admin.sponsors.create')}}">New Sponsors</a></li>
                        <li><a class="disabled" href="{{ '/admin/sponsors/edit/' }}">Edit Sponsor</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage Partners <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.partners.show')}}">Existing Partners</a></li>
                        <li><a href="{{route('admin.partners.create')}}">New Partner</a></li>
                        <li><a class="disabled" href="{{ '/admin/partners/edit/' }}">Edit Partner</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#">manage Registration Plans <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.plans.view')}}">Existing Pricing Plans</a></li>
                        <li><a href="{{route('admin.plan.create')}}">New Pricing Plan</a></li>
                        <li><a href="{{route('admin.PlanOption.create')}}">Add Pricing Plan Options</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage Newsletter Subscribers <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.newsletter.subscribers')}}">View Subscribers</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#"> manage Sliders <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.sliders.show')}}">Existing Slides</a></li>
                        <li><a href="{{route('admin.sliders.create')}}">New Slide</a></li>
                        <li><a class="disabled" href="{{ '/admin/slider/edit/' }}">Edit Slide</a></li>
                    </ul>
                </li>

                <li>
                    <a href="#">Site Settings <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="{{route('admin.settings')}}">Site Settings</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>